name: leader

services:
  postgres:
    container_name: postgres
    env_file:
      - config/config.yaml
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 3s
    ports:
      - "5432:5432"
  role_leader:
    container_name: roleLeader
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
