// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: role-leader.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Feedback      string                 `protobuf:"bytes,7,opt,name=feedback,proto3" json:"feedback,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_role_leader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_role_leader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_role_leader_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Call) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Call) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *Call) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Call) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Call) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *Call) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

type CreateFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedbackRequest) Reset() {
	*x = CreateFeedbackRequest{}
	mi := &file_role_leader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackRequest) ProtoMessage() {}

func (x *CreateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_leader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_role_leader_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFeedbackRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedbackResponse) Reset() {
	*x = CreateFeedbackResponse{}
	mi := &file_role_leader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackResponse) ProtoMessage() {}

func (x *CreateFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_leader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackResponse.ProtoReflect.Descriptor instead.
func (*CreateFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_role_leader_proto_rawDescGZIP(), []int{2}
}

type GetCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallRequest) Reset() {
	*x = GetCallRequest{}
	mi := &file_role_leader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallRequest) ProtoMessage() {}

func (x *GetCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_leader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallRequest.ProtoReflect.Descriptor instead.
func (*GetCallRequest) Descriptor() ([]byte, []int) {
	return file_role_leader_proto_rawDescGZIP(), []int{3}
}

func (x *GetCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type GetCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *Call                  `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallResponse) Reset() {
	*x = GetCallResponse{}
	mi := &file_role_leader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallResponse) ProtoMessage() {}

func (x *GetCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_leader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallResponse.ProtoReflect.Descriptor instead.
func (*GetCallResponse) Descriptor() ([]byte, []int) {
	return file_role_leader_proto_rawDescGZIP(), []int{4}
}

func (x *GetCallResponse) GetCall() *Call {
	if x != nil {
		return x.Call
	}
	return nil
}

type GetLeaderCallsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderCallsRequest) Reset() {
	*x = GetLeaderCallsRequest{}
	mi := &file_role_leader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderCallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderCallsRequest) ProtoMessage() {}

func (x *GetLeaderCallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_leader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderCallsRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderCallsRequest) Descriptor() ([]byte, []int) {
	return file_role_leader_proto_rawDescGZIP(), []int{5}
}

func (x *GetLeaderCallsRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type GetLeaderCallsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calls         []*Call                `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderCallsResponse) Reset() {
	*x = GetLeaderCallsResponse{}
	mi := &file_role_leader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderCallsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderCallsResponse) ProtoMessage() {}

func (x *GetLeaderCallsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_leader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderCallsResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderCallsResponse) Descriptor() ([]byte, []int) {
	return file_role_leader_proto_rawDescGZIP(), []int{6}
}

func (x *GetLeaderCallsResponse) GetCalls() []*Call {
	if x != nil {
		return x.Calls
	}
	return nil
}

var File_role_leader_proto protoreflect.FileDescriptor

const file_role_leader_proto_rawDesc = "" +
	"\n" +
	"\x11role-leader.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\"\xbe\x01\n" +
	"\x04Call\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bfeedback\x18\a \x01(\tR\bfeedback\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\"J\n" +
	"\x15CreateFeedbackRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x18\n" +
	"\x16CreateFeedbackResponse\")\n" +
	"\x0eGetCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"0\n" +
	"\x0fGetCallResponse\x12\x1d\n" +
	"\x04call\x18\x01 \x01(\v2\t.api.CallR\x04call\"4\n" +
	"\x15GetLeaderCallsRequest\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\"9\n" +
	"\x16GetLeaderCallsResponse\x12\x1f\n" +
	"\x05calls\x18\x01 \x03(\v2\t.api.CallR\x05calls2\xc1\x02\n" +
	"\n" +
	"RoleLeader\x12j\n" +
	"\x0eCreateFeedback\x12\x1a.api.CreateFeedbackRequest\x1a\x1b.api.CreateFeedbackResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/create-feedback\x12U\n" +
	"\aGetCall\x12\x13.api.GetCallRequest\x1a\x14.api.GetCallResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/get-call/{call_id}\x12p\n" +
	"\x0eGetLeaderCalls\x12\x1a.api.GetLeaderCallsRequest\x1a\x1b.api.GetLeaderCallsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/leader-calls/{leader_id}B\x0eZ\finternal/apib\x06proto3"

var (
	file_role_leader_proto_rawDescOnce sync.Once
	file_role_leader_proto_rawDescData []byte
)

func file_role_leader_proto_rawDescGZIP() []byte {
	file_role_leader_proto_rawDescOnce.Do(func() {
		file_role_leader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_leader_proto_rawDesc), len(file_role_leader_proto_rawDesc)))
	})
	return file_role_leader_proto_rawDescData
}

var file_role_leader_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_role_leader_proto_goTypes = []any{
	(*Call)(nil),                   // 0: api.Call
	(*CreateFeedbackRequest)(nil),  // 1: api.CreateFeedbackRequest
	(*CreateFeedbackResponse)(nil), // 2: api.CreateFeedbackResponse
	(*GetCallRequest)(nil),         // 3: api.GetCallRequest
	(*GetCallResponse)(nil),        // 4: api.GetCallResponse
	(*GetLeaderCallsRequest)(nil),  // 5: api.GetLeaderCallsRequest
	(*GetLeaderCallsResponse)(nil), // 6: api.GetLeaderCallsResponse
}
var file_role_leader_proto_depIdxs = []int32{
	0, // 0: api.GetCallResponse.call:type_name -> api.Call
	0, // 1: api.GetLeaderCallsResponse.calls:type_name -> api.Call
	1, // 2: api.RoleLeader.CreateFeedback:input_type -> api.CreateFeedbackRequest
	3, // 3: api.RoleLeader.GetCall:input_type -> api.GetCallRequest
	5, // 4: api.RoleLeader.GetLeaderCalls:input_type -> api.GetLeaderCallsRequest
	2, // 5: api.RoleLeader.CreateFeedback:output_type -> api.CreateFeedbackResponse
	4, // 6: api.RoleLeader.GetCall:output_type -> api.GetCallResponse
	6, // 7: api.RoleLeader.GetLeaderCalls:output_type -> api.GetLeaderCallsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_role_leader_proto_init() }
func file_role_leader_proto_init() {
	if File_role_leader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_leader_proto_rawDesc), len(file_role_leader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_leader_proto_goTypes,
		DependencyIndexes: file_role_leader_proto_depIdxs,
		MessageInfos:      file_role_leader_proto_msgTypes,
	}.Build()
	File_role_leader_proto = out.File
	file_role_leader_proto_goTypes = nil
	file_role_leader_proto_depIdxs = nil
}
