// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: api/role-leader.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Feedback      string                 `protobuf:"bytes,7,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_api_role_leader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_leader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_api_role_leader_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Call) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Call) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *Call) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Call) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Call) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Call) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

type CreateFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedbackRequest) Reset() {
	*x = CreateFeedbackRequest{}
	mi := &file_api_role_leader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackRequest) ProtoMessage() {}

func (x *CreateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_leader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_api_role_leader_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFeedbackRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedbackResponse) Reset() {
	*x = CreateFeedbackResponse{}
	mi := &file_api_role_leader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackResponse) ProtoMessage() {}

func (x *CreateFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_leader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackResponse.ProtoReflect.Descriptor instead.
func (*CreateFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_api_role_leader_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFeedbackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallRequest) Reset() {
	*x = GetCallRequest{}
	mi := &file_api_role_leader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallRequest) ProtoMessage() {}

func (x *GetCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_leader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallRequest.ProtoReflect.Descriptor instead.
func (*GetCallRequest) Descriptor() ([]byte, []int) {
	return file_api_role_leader_proto_rawDescGZIP(), []int{3}
}

func (x *GetCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type GetCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *Call                  `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallResponse) Reset() {
	*x = GetCallResponse{}
	mi := &file_api_role_leader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallResponse) ProtoMessage() {}

func (x *GetCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_role_leader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallResponse.ProtoReflect.Descriptor instead.
func (*GetCallResponse) Descriptor() ([]byte, []int) {
	return file_api_role_leader_proto_rawDescGZIP(), []int{4}
}

func (x *GetCallResponse) GetCall() *Call {
	if x != nil {
		return x.Call
	}
	return nil
}

var File_api_role_leader_proto protoreflect.FileDescriptor

const file_api_role_leader_proto_rawDesc = "" +
	"\n" +
	"\x15api/role-leader.proto\x1a#api/google/protobuf/timestamp.proto\"\xda\x01\n" +
	"\x04Call\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bfeedback\x18\a \x01(\tR\bfeedback\"J\n" +
	"\x15CreateFeedbackRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x16CreateFeedbackResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\")\n" +
	"\x0eGetCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\",\n" +
	"\x0fGetCallResponse\x12\x19\n" +
	"\x04call\x18\x01 \x01(\v2\x05.CallR\x04call2}\n" +
	"\n" +
	"RoleLeader\x12A\n" +
	"\x0eCreateFeedback\x12\x16.CreateFeedbackRequest\x1a\x17.CreateFeedbackResponse\x12,\n" +
	"\aGetCall\x12\x0f.GetCallRequest\x1a\x10.GetCallResponseB\x0eZ\finternal/apib\x06proto3"

var (
	file_api_role_leader_proto_rawDescOnce sync.Once
	file_api_role_leader_proto_rawDescData []byte
)

func file_api_role_leader_proto_rawDescGZIP() []byte {
	file_api_role_leader_proto_rawDescOnce.Do(func() {
		file_api_role_leader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_role_leader_proto_rawDesc), len(file_api_role_leader_proto_rawDesc)))
	})
	return file_api_role_leader_proto_rawDescData
}

var file_api_role_leader_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_role_leader_proto_goTypes = []any{
	(*Call)(nil),                   // 0: Call
	(*CreateFeedbackRequest)(nil),  // 1: CreateFeedbackRequest
	(*CreateFeedbackResponse)(nil), // 2: CreateFeedbackResponse
	(*GetCallRequest)(nil),         // 3: GetCallRequest
	(*GetCallResponse)(nil),        // 4: GetCallResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_api_role_leader_proto_depIdxs = []int32{
	5, // 0: Call.start_time:type_name -> google.protobuf.Timestamp
	0, // 1: GetCallResponse.call:type_name -> Call
	1, // 2: RoleLeader.CreateFeedback:input_type -> CreateFeedbackRequest
	3, // 3: RoleLeader.GetCall:input_type -> GetCallRequest
	2, // 4: RoleLeader.CreateFeedback:output_type -> CreateFeedbackResponse
	4, // 5: RoleLeader.GetCall:output_type -> GetCallResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_role_leader_proto_init() }
func file_api_role_leader_proto_init() {
	if File_api_role_leader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_role_leader_proto_rawDesc), len(file_api_role_leader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_role_leader_proto_goTypes,
		DependencyIndexes: file_api_role_leader_proto_depIdxs,
		MessageInfos:      file_api_role_leader_proto_msgTypes,
	}.Build()
	File_api_role_leader_proto = out.File
	file_api_role_leader_proto_goTypes = nil
	file_api_role_leader_proto_depIdxs = nil
}
