POSTGRES:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: root
  POSTGRES_PASSWORD: 1234
  POSTGRES_DB: postgres
  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5
GRPC:
  ROLE_LEADER_GRPC_PORT: 50051
LOGGER:
  ENV: local
